"""agregado tipo a movimientos proveedor

Revision ID: 063ab41b1afa
Revises: aa964713f342
Create Date: 2026-08-25 12:46:49.738656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063ab41b1afa'
down_revision = 'aa964713f342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_cta_cte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_movimiento_cta_cte_sucursal_id_sucursal'), 'sucursal', ['sucursal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_cta_cte', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movimiento_cta_cte_sucursal_id_sucursal'), type_='foreignkey')
        batch_op.drop_column('sucursal_id')

    # ### end Alembic commands ###
