"""Relaciones de stock corregidas

Revision ID: 84015d97b9ef
Revises: 
Create Date: 2026-08-13 11:07:39.156883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84015d97b9ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria_movimiento'))
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('condicion_iva', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('iibb', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cliente')),
    sa.UniqueConstraint('cuit', name=op.f('uq_cliente_cuit'))
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa')),
    sa.UniqueConstraint('cuit', name=op.f('uq_empresa_cuit'))
    )
    op.create_table('modelo_auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('anio_inicio', sa.Integer(), nullable=True),
    sa.Column('anio_fin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modelo_auto'))
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('condicion_iva', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('iibb', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedor')),
    sa.UniqueConstraint('cuit', name=op.f('uq_proveedor_cuit'))
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('nro_factura', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('iva_porcentaje', sa.Float(), nullable=True),
    sa.Column('impuestos_monto', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('plazo_pago', sa.Integer(), nullable=True),
    sa.Column('total_pagado', sa.Float(), nullable=True),
    sa.Column('esta_pagada', sa.Boolean(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name=op.f('fk_compra_proveedor_id_proveedor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compra'))
    )
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('celular_alternativo', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_sucursal_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sucursal'))
    )
    op.create_table('caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('saldo_actual', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_caja_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caja'))
    )
    op.create_table('movimiento_cta_cte_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('pago_prov_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], name=op.f('fk_movimiento_cta_cte_proveedor_compra_id_compra')),
    sa.ForeignKeyConstraint(['pago_prov_id'], ['movimiento_cta_cte_proveedor.id'], name=op.f('fk_movimiento_cta_cte_proveedor_pago_prov_id_movimiento_cta_cte_proveedor')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name=op.f('fk_movimiento_cta_cte_proveedor_proveedor_id_proveedor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento_cta_cte_proveedor'))
    )
    op.create_table('repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('sku_vacan', sa.String(length=50), nullable=True),
    sa.Column('codigo_oem', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('subrubro', sa.String(length=100), nullable=True),
    sa.Column('sku_denso', sa.String(length=50), nullable=True),
    sa.Column('sku_cromosol', sa.String(length=50), nullable=True),
    sa.Column('sku_expoyer', sa.String(length=50), nullable=True),
    sa.Column('sku_repuestos_jl', sa.String(length=50), nullable=True),
    sa.Column('sku_facor', sa.String(length=50), nullable=True),
    sa.Column('sku_altri', sa.String(length=50), nullable=True),
    sa.Column('sku_rosparts', sa.String(length=50), nullable=True),
    sa.Column('otros_codigos', sa.Text(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name=op.f('fk_repuesto_proveedor_id_proveedor')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_repuesto_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repuesto'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_usuario_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('username', name=op.f('uq_usuario_username'))
    )
    op.create_table('cierre_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('saldo_esperado', sa.Float(), nullable=False),
    sa.Column('saldo_real', sa.Float(), nullable=False),
    sa.Column('diferencia', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['caja_id'], ['caja.id'], name=op.f('fk_cierre_caja_caja_id_caja')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_cierre_caja_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cierre_caja'))
    )
    op.create_table('compatibilidad',
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('modelo_auto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_auto_id'], ['modelo_auto.id'], name=op.f('fk_compatibilidad_modelo_auto_id_modelo_auto')),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], name=op.f('fk_compatibilidad_repuesto_id_repuesto')),
    sa.PrimaryKeyConstraint('repuesto_id', 'modelo_auto_id', name=op.f('pk_compatibilidad'))
    )
    op.create_table('detalle_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=True),
    sa.Column('nombre_item', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], name=op.f('fk_detalle_compra_compra_id_compra')),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], name=op.f('fk_detalle_compra_repuesto_id_repuesto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_compra'))
    )
    op.create_table('historial_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('costo_anterior', sa.Float(), nullable=True),
    sa.Column('costo_nuevo', sa.Float(), nullable=True),
    sa.Column('precio_anterior', sa.Float(), nullable=True),
    sa.Column('precio_nuevo', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], name=op.f('fk_historial_precio_repuesto_id_repuesto')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_historial_precio_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historial_precio'))
    )
    op.create_table('presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_presupuesto_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_presupuesto_sucursal_id_sucursal')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_presupuesto_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presupuesto'))
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=20), nullable=True),
    sa.Column('metodo_pago', sa.String(length=20), nullable=True),
    sa.Column('estado_arca', sa.String(length=20), nullable=True),
    sa.Column('esta_pagada', sa.Boolean(), nullable=True),
    sa.Column('total_pagado', sa.Float(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_venta_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_venta_sucursal_id_sucursal')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_venta_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta'))
    )
    op.create_table('cheque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('emisor', sa.String(length=150), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('pago_prov_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_cheque_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['pago_prov_id'], ['movimiento_cta_cte_proveedor.id'], name=op.f('fk_cheque_pago_prov_id_movimiento_cta_cte_proveedor')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name=op.f('fk_cheque_proveedor_id_proveedor')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_cheque_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cheque'))
    )
    op.create_table('detalle_presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=True),
    sa.Column('nombre_item', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_pactado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuesto.id'], name=op.f('fk_detalle_presupuesto_presupuesto_id_presupuesto')),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], name=op.f('fk_detalle_presupuesto_repuesto_id_repuesto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_presupuesto'))
    )
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=True),
    sa.Column('nombre_item', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], name=op.f('fk_detalle_venta_repuesto_id_repuesto')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_detalle_venta_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_venta'))
    )
    op.create_table('movimiento_cta_cte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_movimiento_cta_cte_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_movimiento_cta_cte_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento_cta_cte'))
    )
    op.create_table('movimiento_financiero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('metodo_detalle', sa.String(length=50), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('pago_prov_id', sa.Integer(), nullable=True),
    sa.Column('es_transferencia', sa.Boolean(), nullable=True),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['caja_id'], ['caja.id'], name=op.f('fk_movimiento_financiero_caja_id_caja')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_movimiento.id'], name=op.f('fk_movimiento_financiero_categoria_id_categoria_movimiento')),
    sa.ForeignKeyConstraint(['pago_prov_id'], ['movimiento_cta_cte_proveedor.id'], name=op.f('fk_movimiento_financiero_pago_prov_id_movimiento_cta_cte_proveedor')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_movimiento_financiero_usuario_id_usuario')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_movimiento_financiero_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento_financiero'))
    )
    op.create_table('pago_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('nro_comprobante', sa.String(length=100), nullable=True),
    sa.Column('cuotas', sa.Integer(), nullable=True),
    sa.Column('interes', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_pago_venta_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pago_venta'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago_venta')
    op.drop_table('movimiento_financiero')
    op.drop_table('movimiento_cta_cte')
    op.drop_table('detalle_venta')
    op.drop_table('detalle_presupuesto')
    op.drop_table('cheque')
    op.drop_table('venta')
    op.drop_table('presupuesto')
    op.drop_table('historial_precio')
    op.drop_table('detalle_compra')
    op.drop_table('compatibilidad')
    op.drop_table('cierre_caja')
    op.drop_table('usuario')
    op.drop_table('repuesto')
    op.drop_table('movimiento_cta_cte_proveedor')
    op.drop_table('caja')
    op.drop_table('sucursal')
    op.drop_table('compra')
    op.drop_table('proveedor')
    op.drop_table('modelo_auto')
    op.drop_table('empresa')
    op.drop_table('cliente')
    op.drop_table('categoria_movimiento')
    # ### end Alembic commands ###
