"""módulo traspasos

Revision ID: 929cfcd097ce
Revises: 84015d97b9ef
Create Date: 2026-08-24 07:46:40.541998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929cfcd097ce'
down_revision = '84015d97b9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traspaso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('sucursal_origen_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_destino_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_destino_id'], ['sucursal.id'], name=op.f('fk_traspaso_sucursal_destino_id_sucursal')),
    sa.ForeignKeyConstraint(['sucursal_origen_id'], ['sucursal.id'], name=op.f('fk_traspaso_sucursal_origen_id_sucursal')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_traspaso_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traspaso'))
    )
    op.create_table('detalle_traspaso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traspaso_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], name=op.f('fk_detalle_traspaso_repuesto_id_repuesto')),
    sa.ForeignKeyConstraint(['traspaso_id'], ['traspaso.id'], name=op.f('fk_detalle_traspaso_traspaso_id_traspaso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_traspaso'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_traspaso')
    op.drop_table('traspaso')
    # ### end Alembic commands ###
