"""margen compras

Revision ID: 997b4a15dc4a
Revises: f7a690c2808c
Create Date: 2026-08-24 10:15:29.307467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997b4a15dc4a'
down_revision = 'f7a690c2808c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_comprobante', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_column('tipo_comprobante')

    # ### end Alembic commands ###
