"""agregado tipo a movimientos proveedor

Revision ID: 9ba4cdd4d3b0
Revises: 063ab41b1afa
Create Date: 2026-08-25 13:23:03.200689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba4cdd4d3b0'
down_revision = '063ab41b1afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_cta_cte_proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_movimiento_cta_cte_proveedor_sucursal_id_sucursal'), 'sucursal', ['sucursal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_cta_cte_proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movimiento_cta_cte_proveedor_sucursal_id_sucursal'), type_='foreignkey')
        batch_op.drop_column('sucursal_id')

    # ### end Alembic commands ###
