"""agregado tipo a movimientos proveedor

Revision ID: aa964713f342
Revises: 997b4a15dc4a
Create Date: 2026-08-24 11:50:08.039133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa964713f342'
down_revision = '997b4a15dc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_cta_cte_proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_cta_cte_proveedor', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
