"""agregado tipo a movimientos proveedor

Revision ID: d573d4c6f9fb
Revises: 9ba4cdd4d3b0
Create Date: 2026-08-27 15:25:36.977385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd573d4c6f9fb'
down_revision = '9ba4cdd4d3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.drop_column('ubicacion')

    # ### end Alembic commands ###
