"""margen compras

Revision ID: f7a690c2808c
Revises: 929cfcd097ce
Create Date: 2026-08-24 08:16:38.179075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a690c2808c'
down_revision = '929cfcd097ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('margen_sugerido', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_column('margen_sugerido')

    # ### end Alembic commands ###
